# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Integration tests

on:
  pull_request:
    branches: [ deploy ]

jobs:
  linting:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: 'npm'
      - name: install packages
        run: npm install
      - name: lint
        run:  npm run lint
